### ISSUE TITLE
Trying to retrieve favorites in mobile app crashes the app

### ISSUE THREAD

**Issue by caseda** [nlrb/com.soundunited.heos#1]
Thanks for the awesome work on this app! works way better then Athom's.

Did find an issue though, if i try to create an action card: playing a favorite, and then it retrieves the favorites. it will completely blank out the _entire homey mobile app_, thus crashing the homey app.
Seems like something kicks the connection right after retrieving the favorites, and the app doesn't like that:
```
[3] Result [ { image: '', name: 'NPO 3FM', type: 'station', preset: 1 } ]
2020-01-30 20:06:57 [log] [ManagerDrivers] [heos] Connection failed: { Error: This socket has been ended by the other party
    at Socket.writeAfterFIN [as write] (net.js:376:12)
    at DenonHeos._write (/node_modules/denon-heos/lib/DenonHeos.js:199:16)
    at DenonHeos._nextSendQueueItem (/node_modules/denon-heos/lib/DenonHeos.js:115:28)
    at DenonHeos.send (/node_modules/denon-heos/lib/DenonHeos.js:53:8)
    at Timeout._timer.setInterval (/node_modules/denon-heos/lib/DenonHeos.js:70:42)
    at ontimeout (timers.js:498:11)
    at tryOnTimeout (timers.js:323:5)
    at Timer.listOnTimeout (timers.js:290:5) code: 'EPIPE' }
```

It only does this in the mobile app, for some reason the web editor doesn't have this issue.
Heos app version 1.1.3

Let me know if you need any more information.

**Comment by nlrb** [comment]
Hi, thanks for reporting. I noticed this myself as well, but the issue is the way the mobile app handles images.

You will get this when an item contains `image: ''`.

I can create a workaround by not creating an `image` element in that case, but according to the API (and web app), it should not be needed.

BTW: the web app does not show any image (also not from valid URLs), whilst the web version does show them OK.

IMHO Athom should fix their mobile app.
